language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.9 DB=postgres

# command to install dependencies
install: 
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install pylint

# command to run tests
script: pylint ./djangocrud/ --ignore=migrations