# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20150910_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[(b'PB', b'Public'), (b'PR', b'Private')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
