# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import djangocrud.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supplier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[(b'PB', b'Public'), (b'PR', b'Private')], max_length=10, verbose_name=b'Category/Type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Creation Date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Last Updated'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, validators=[djangocrud.core.validators.validate_name], verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remarks',
            field=models.TextField(blank=True, default=0, verbose_name=b'Remarks'),
            preserve_default=False,
        ),
    ]
